/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_high_score_30 (
    input [6:0] player_current_score,
    input [6:0] high_score,
    output reg high_score_lower
  );
  
  
  
  wire [16-1:0] M_alu_aluOut;
  wire [1-1:0] M_alu_z;
  wire [1-1:0] M_alu_v;
  wire [1-1:0] M_alu_n;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn;
  alu_41 alu (
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn(M_alu_alufn),
    .aluOut(M_alu_aluOut),
    .z(M_alu_z),
    .v(M_alu_v),
    .n(M_alu_n)
  );
  
  always @* begin
    high_score_lower = 1'h0;
    M_alu_a = high_score;
    M_alu_b = player_current_score;
    M_alu_alufn = 6'h35;
    high_score_lower = M_alu_aluOut[0+0-:1];
  end
endmodule
