/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_seven_seg_1 (
    input [3:0] to_display,
    output reg [7:0] to_seven_seg
  );
  
  
  
  always @* begin
    to_seven_seg = 8'h00;
    
    case (to_display)
      4'h0: begin
        to_seven_seg = 8'h7e;
      end
      4'h1: begin
        to_seven_seg = 8'h06;
      end
      4'h2: begin
        to_seven_seg = 8'hbc;
      end
      4'h3: begin
        to_seven_seg = 8'h9e;
      end
      4'h4: begin
        to_seven_seg = 8'hc6;
      end
      4'h5: begin
        to_seven_seg = 8'hda;
      end
      4'h6: begin
        to_seven_seg = 8'hfa;
      end
      4'h7: begin
        to_seven_seg = 8'h0e;
      end
      4'h8: begin
        to_seven_seg = 8'hfe;
      end
      4'h9: begin
        to_seven_seg = 8'hce;
      end
      default: begin
        to_seven_seg = 8'h7e;
      end
    endcase
  end
endmodule
