/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module game_states_2 (
    input clk,
    input rst,
    output reg [63:0] player_position_out,
    input button_up,
    input button_down,
    input button_left,
    input button_right
  );
  
  
  
  
  localparam START_state = 1'd0;
  localparam MOVE_state = 1'd1;
  
  reg M_state_d, M_state_q = START_state;
  
  reg [63:0] M_player_position_d, M_player_position_q = 8'h80;
  
  reg [2:0] M_player_reg_selector_d, M_player_reg_selector_q = 1'h0;
  
  reg [63:0] next_position;
  
  wire [64-1:0] M_inter_one_player_initial_position;
  wire [3-1:0] M_inter_one_player_reg_selector;
  wire [64-1:0] M_inter_one_end_position;
  wire [64-1:0] M_inter_one_walls;
  level_one_rom_11 inter_one (
    .player_initial_position(M_inter_one_player_initial_position),
    .player_reg_selector(M_inter_one_player_reg_selector),
    .end_position(M_inter_one_end_position),
    .walls(M_inter_one_walls)
  );
  
  wire [64-1:0] M_move_player_player_location_out;
  wire [3-1:0] M_move_player_new_player_reg_selector;
  reg [1-1:0] M_move_player_button_up;
  reg [1-1:0] M_move_player_button_down;
  reg [1-1:0] M_move_player_button_left;
  reg [1-1:0] M_move_player_button_right;
  reg [3-1:0] M_move_player_player_reg_selector;
  reg [64-1:0] M_move_player_player_current_position;
  move_player_12 move_player (
    .button_up(M_move_player_button_up),
    .button_down(M_move_player_button_down),
    .button_left(M_move_player_button_left),
    .button_right(M_move_player_button_right),
    .player_reg_selector(M_move_player_player_reg_selector),
    .player_current_position(M_move_player_player_current_position),
    .player_location_out(M_move_player_player_location_out),
    .new_player_reg_selector(M_move_player_new_player_reg_selector)
  );
  
  always @* begin
    M_state_d = M_state_q;
    M_player_position_d = M_player_position_q;
    M_player_reg_selector_d = M_player_reg_selector_q;
    
    player_position_out = 64'h0000000000000000;
    M_move_player_button_down = 1'h0;
    M_move_player_button_left = 1'h0;
    M_move_player_button_right = 1'h0;
    M_move_player_button_up = 1'h0;
    M_move_player_player_reg_selector = 3'bxxx;
    M_move_player_player_current_position = 64'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
    next_position = 64'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
    M_player_position_d = M_player_position_q;
    M_player_reg_selector_d = M_player_reg_selector_q;
    
    case (M_state_q)
      START_state: begin
        M_player_position_d = M_inter_one_player_initial_position;
        M_player_reg_selector_d = M_inter_one_player_reg_selector;
        player_position_out = M_player_position_q;
        M_state_d = MOVE_state;
      end
      MOVE_state: begin
        if (button_up) begin
          M_move_player_button_up = 1'h1;
          M_move_player_player_current_position = M_player_position_q;
          M_move_player_player_reg_selector = M_player_reg_selector_q;
          M_player_reg_selector_d = M_move_player_new_player_reg_selector;
          next_position = M_move_player_player_location_out;
        end
        if (button_down) begin
          M_move_player_button_down = 1'h1;
          M_move_player_player_reg_selector = M_player_reg_selector_q;
          M_move_player_player_current_position = M_player_position_q;
          M_player_reg_selector_d = M_move_player_new_player_reg_selector;
          next_position = M_move_player_player_location_out;
        end
        if (button_left) begin
          M_move_player_button_left = 1'h1;
          M_move_player_player_current_position = M_player_position_q;
          M_move_player_player_reg_selector = M_player_reg_selector_q;
          M_player_reg_selector_d = M_move_player_new_player_reg_selector;
          next_position = M_move_player_player_location_out;
        end
        if (button_right) begin
          M_move_player_button_right = 1'h1;
          M_move_player_player_current_position = M_player_position_q;
          M_move_player_player_reg_selector = M_player_reg_selector_q;
          M_player_reg_selector_d = M_move_player_new_player_reg_selector;
          next_position = M_move_player_player_location_out;
        end
        M_player_position_d = next_position;
        player_position_out = next_position;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_player_reg_selector_q <= 1'h0;
    end else begin
      M_player_reg_selector_q <= M_player_reg_selector_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_player_position_q <= 8'h80;
    end else begin
      M_player_position_q <= M_player_position_d;
    end
  end
  
  
  always @(posedge clk) begin
    M_state_q <= M_state_d;
  end
  
endmodule
