/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [7:0] green,
    output reg [7:0] col
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  reg [31:0] M_counter_d, M_counter_q = 1'h0;
  
  always @* begin
    M_counter_d = M_counter_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    col = 8'h00;
    green = 8'h00;
    M_counter_d = M_counter_q + 1'h1;
    col[0+0-:1] = M_counter_q[23+0-:1];
    col[1+0-:1] = M_counter_q[24+0-:1];
    col[2+0-:1] = M_counter_q[25+0-:1];
    col[3+0-:1] = M_counter_q[26+0-:1];
    col[4+0-:1] = M_counter_q[27+0-:1];
    col[5+0-:1] = M_counter_q[28+0-:1];
    col[6+0-:1] = M_counter_q[29+0-:1];
    col[7+0-:1] = M_counter_q[30+0-:1];
  end
  
  always @(posedge clk) begin
    M_counter_q <= M_counter_d;
  end
  
endmodule
