/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module move_player_12 (
    input [2:0] player_reg_selector,
    input [63:0] player_current_position,
    output reg [63:0] player_location_out,
    output reg [2:0] new_player_reg_selector
  );
  
  
  
  always @* begin
    new_player_reg_selector = player_reg_selector;
    player_location_out = 64'h0000000000000000;
    
    case (player_reg_selector)
      3'h0: begin
        player_location_out[0+7-:8] = player_current_position[0+7-:8];
        new_player_reg_selector = 3'h0;
      end
      3'h1: begin
        player_location_out[0+7-:8] = player_current_position[8+7-:8];
        new_player_reg_selector = 3'h0;
      end
      3'h2: begin
        player_location_out[8+7-:8] = player_current_position[16+7-:8];
        new_player_reg_selector = 3'h1;
      end
      3'h3: begin
        player_location_out[16+7-:8] = player_current_position[24+7-:8];
        new_player_reg_selector = 3'h2;
      end
      3'h4: begin
        player_location_out[24+7-:8] = player_current_position[32+7-:8];
        new_player_reg_selector = 3'h3;
      end
      3'h5: begin
        player_location_out[32+7-:8] = player_current_position[40+7-:8];
        new_player_reg_selector = 3'h4;
      end
      3'h6: begin
        player_location_out[40+7-:8] = player_current_position[48+7-:8];
        new_player_reg_selector = 3'h5;
      end
      3'h7: begin
        player_location_out[48+7-:8] = player_current_position[56+7-:8];
        new_player_reg_selector = 3'h6;
      end
    endcase
  end
endmodule
