/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module wall_collide_21 (
    input [7:0] player_current_position,
    input [7:0] walls,
    output reg collide
  );
  
  
  
  wire [16-1:0] M_alu_aluOut;
  wire [1-1:0] M_alu_z;
  wire [1-1:0] M_alu_v;
  wire [1-1:0] M_alu_n;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn;
  alu_25 alu (
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn(M_alu_alufn),
    .aluOut(M_alu_aluOut),
    .z(M_alu_z),
    .v(M_alu_v),
    .n(M_alu_n)
  );
  
  reg [7:0] new_player_loc;
  
  always @* begin
    collide = 1'h1;
    M_alu_a = player_current_position;
    M_alu_b = walls;
    M_alu_alufn = 6'h18;
    new_player_loc = M_alu_aluOut[0+7-:8];
    if (new_player_loc == 8'h00) begin
      collide = 1'h0;
    end else begin
      collide = 1'h1;
    end
  end
endmodule
